version: "3.8"
services:
  client:
    image: node:14.6.0-slim
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/my-app/node_modules
    ports:
      - 3000:3000
    networks:
      - frontend
    tty: true

networks:
  frontend:
