name: Textlint
on: [pull_request]

jobs:
  lint:
    name: Textlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: textlint-github-pr-review
        uses: tsuyoshicho/action-textlint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          textlint_flags: "src/**/*.md"
